// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5d9ea64DecodeGithubComMorphcloudCustomerServiceInternalAppDomain(in *jlexer.Lexer, out *Customer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "firstName":
			out.FirstName = string(in.String())
		case "middleName":
			out.MiddleName = string(in.String())
		case "lastName":
			out.LastName = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "statusId":
			out.StatusID = int32(in.Int32())
		case "createdAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d9ea64EncodeGithubComMorphcloudCustomerServiceInternalAppDomain(out *jwriter.Writer, in Customer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.FirstName != "" {
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	if in.MiddleName != "" {
		const prefix string = ",\"middleName\":"
		out.RawString(prefix)
		out.String(string(in.MiddleName))
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"statusId\":"
		out.RawString(prefix)
		out.Int32(int32(in.StatusID))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Customer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d9ea64EncodeGithubComMorphcloudCustomerServiceInternalAppDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Customer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d9ea64EncodeGithubComMorphcloudCustomerServiceInternalAppDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Customer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d9ea64DecodeGithubComMorphcloudCustomerServiceInternalAppDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Customer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d9ea64DecodeGithubComMorphcloudCustomerServiceInternalAppDomain(l, v)
}
