// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  v1

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( RegistrationRequestBody ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegistrationRequestBody ) UnmarshalJSON([]byte) error { return nil }
func ( RegistrationRequestBody ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegistrationRequestBody ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegistrationRequestBody *RegistrationRequestBody

func ( customerHandler ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* customerHandler ) UnmarshalJSON([]byte) error { return nil }
func ( customerHandler ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* customerHandler ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_customerHandler *customerHandler
