apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: hzhyvinskyi/morphcloud-customer-service:1.0.0
        env:
        - name: APP_NAME
          value: customer-service
        - name: PORT
          value: 8082
