apiVersion: v1
kind: Service
metadata:
  name: morphcloud-customer-postgres
  labels:
    app: customer-postgres
spec:
  selector:
    app: customer-postgres
  ports:
    - port: 5432
  type: ClusterIP
