apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  selector:
    matchLabels:
      app: customer
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: hzhyvinskyi/morphcloud-customer-service:1.0.0
        env:
        - name: APP_NAME
          value: "Customer Service"
        - name: HOSTNAME
          value: "customer"
        - name: PORT
          value: "8082"
        - name: POSTGRES_HOST
          value: "morphcloud-customer-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "customer-db-user"
        - name: POSTGRES_PASS
          value: "customer-db-pwd"
        - name: POSTGRES_DB
          value: "customer-db"
